// <auto-generated />
using System;
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ReceptSystemContext))]
    [Migration("20251210095039_RettetForetagne")]
    partial class RettetForetagne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Model.Apotek", b =>
                {
                    b.Property<Guid>("ApotekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApotekId");

                    b.ToTable("Apoteker");
                });

            modelBuilder.Entity("DAL.Model.Lægehus", b =>
                {
                    b.Property<int>("Ydernummer")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ydernummer");

                    b.ToTable("Lægehuse");
                });

            modelBuilder.Entity("DAL.Model.Ordination", b =>
                {
                    b.Property<Guid>("OrdinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AntalForetagneUdleveringer")
                        .HasColumnType("int");

                    b.Property<int>("AntalUdleveringer")
                        .HasColumnType("int");

                    b.Property<string>("Dosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lægemiddel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReceptId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrdinationId");

                    b.HasIndex("ReceptId");

                    b.ToTable("Ordinationer");
                });

            modelBuilder.Entity("DAL.Model.Recept", b =>
                {
                    b.Property<Guid>("ReceptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Lukket")
                        .HasColumnType("bit");

                    b.Property<int>("LægehusYdernummer")
                        .HasColumnType("int");

                    b.Property<DateTime>("OprettelsesDato")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientCpr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReceptId");

                    b.HasIndex("LægehusYdernummer");

                    b.ToTable("Recepter");
                });

            modelBuilder.Entity("DAL.Model.ReceptUdlevering", b =>
                {
                    b.Property<Guid>("ReceptUdleveringId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApotekId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReceptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UdleveringsDato")
                        .HasColumnType("datetime2");

                    b.HasKey("ReceptUdleveringId");

                    b.HasIndex("ApotekId");

                    b.HasIndex("ReceptId");

                    b.ToTable("ReceptUdleveringer");
                });

            modelBuilder.Entity("DAL.Model.Ordination", b =>
                {
                    b.HasOne("DAL.Model.Recept", null)
                        .WithMany("Ordinationer")
                        .HasForeignKey("ReceptId");
                });

            modelBuilder.Entity("DAL.Model.Recept", b =>
                {
                    b.HasOne("DAL.Model.Lægehus", "Lægehus")
                        .WithMany("Recepter")
                        .HasForeignKey("LægehusYdernummer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lægehus");
                });

            modelBuilder.Entity("DAL.Model.ReceptUdlevering", b =>
                {
                    b.HasOne("DAL.Model.Apotek", "Apotek")
                        .WithMany("ReceptUdleveringer")
                        .HasForeignKey("ApotekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Model.Recept", "Recept")
                        .WithMany("ReceptUdleveringer")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apotek");

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("DAL.Model.Apotek", b =>
                {
                    b.Navigation("ReceptUdleveringer");
                });

            modelBuilder.Entity("DAL.Model.Lægehus", b =>
                {
                    b.Navigation("Recepter");
                });

            modelBuilder.Entity("DAL.Model.Recept", b =>
                {
                    b.Navigation("Ordinationer");

                    b.Navigation("ReceptUdleveringer");
                });
#pragma warning restore 612, 618
        }
    }
}
